# Generated by Django 4.0.2 on 2022-04-12 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=250)),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=250)),
                ('ano', models.IntegerField(blank=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tipo.tipo')),
            ],
            options={
                'db_table': 'referencia',
            },
        ),
    ]
