# Generated by Django 4.0.2 on 2022-04-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='script',
            field=models.CharField(db_index=True, default='nome do script python', max_length=50),
        ),
    ]
