# Generated by Django 4.0.2 on 2023-01-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='name',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
    ]
