# Generated by Django 4.0.2 on 2023-01-06 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_alter_tutorial_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='year',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
