# Generated by Django 4.0.2 on 2023-01-06 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_remove_tutorial_year_tutorial_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='last_updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
