# Generated by Django 4.0.2 on 2023-01-06 19:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='referenceds', to='tutorial.tutorial')),
                ('referenced', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='origins', to='tutorial.tutorial')),
            ],
            options={
                'db_table': 'tutorialtutorial',
            },
        ),
    ]
