# Generated by Django 4.0.2 on 2022-04-14 02:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('tutorial_origem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutoriais_refs', to='tutorial.tutorial')),
                ('tutorial_referencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutoriais_origens', to='tutorial.tutorial')),
            ],
            options={
                'db_table': 'tutorial_tutorial',
            },
        ),
    ]
