# Generated by Django 4.0.2 on 2022-04-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sigla', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
            options={
                'db_table': 'termo',
            },
        ),
    ]
