# Generated by Django 4.0.2 on 2022-04-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=250)),
                ('link_base', models.CharField(blank=True, max_length=250)),
                ('link_descricao', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'base',
                'ordering': ('nome',),
            },
        ),
    ]
