# Generated by Django 4.0.2 on 2022-04-14 01:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artigo', '0001_initial'),
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=250)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artigo.artigo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autor.autor')),
            ],
            options={
                'db_table': 'artigo_autor',
                'ordering': ('nome',),
            },
        ),
    ]
