# Generated by Django 4.0.2 on 2022-04-14 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artigo_autor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigoautor',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
