# Generated by Django 4.0.2 on 2022-04-14 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('autor', '0001_initial'),
        ('base_autor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseautor',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='baseautor2', to='autor.autor'),
        ),
        migrations.AlterField(
            model_name='baseautor',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='baseautor1', to='base.base'),
        ),
    ]
