# Generated by Django 4.0.2 on 2023-01-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialbook',
            name='cited',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
